# Site title and subtitle. This is used in _includes/header.html
title: 'docs.csirtgadgets.org'
menutitle: 'menu'

# URL to source code, used in _includes/footer.html
siteurl: 'docs.csirtgadgets.org' 
assetsurl: 'https://csirtgadgets.github.io'
baseurl: '/'
#siteurl: 'http://0.0.0.0:4000'

permalink: none

# Exclude non-site files
exclude: ['bin', 'README.md']

post_limit: 7 

sections: [
    ['post', 'Posts'],
    ['proj', 'Projects'],
    ['snip', 'Snippets'],
    ['howto', 'HowTo'],
]

# Use the redcarpet Markdown renderer
markdown: redcarpet
gems:
    - jekyll-mentions
